### ISSUE TITLE
Timeline for 1.0?

### ISSUE THREAD

**Issue by deeplook** [darribas/contextily#121] opened 2020-02-13 09:35 UTC
I was looking at 1.0rc2 which looks really promising. Thanks a lot! Is there a timeline for a proper 1.0 release?

**Comment by darribas** [comment] 2020-02-14 10:13
thanks very much for the interest and the kind words! Yes, the only thing @jorisvandenbossche, @ljwolf and I want to fully flesh out for 1.0 is the new provider API. We have a sketch in `rc2` so it probably won't change much. The main constrain now is time to decide what to do exactly (which should not be much work) and push out the official release. I'm not going to give timelines, but probably over the summer? Maybe a bit earlier but summer for sure :)

**Comment by jorisvandenbossche** [comment] 2020-02-14 10:16
Let's close this as a duplicate of https://github.com/darribas/contextily/issues/109, can continue the discussion there

**Closed by jorisvandenbossche** 2020-02-14 10:16 UTC
